language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-5.1.x
script: bundle exec rspec spec
